---
kind: pipeline
name: default

steps:
- name: "set image tags"
  image: bash
  environment:
    IRCD_VERSION: "3.9.0"
  # Build the following tags: maj.min.patch, maj.min.patch-YYMMDD, maj, maj.min, latest
  commands:
    - >
     bash -c 'echo "$IRCD_VERSION,$IRCD_VERSION-$(date +%Y%m%d),$(cut -d . -f 1 <<< $IRCD_VERSION),$(cut -d . -f 1,2 <<< $IRCD_VERSION),latest" > .tags'

- name: "build docker"
  # Custom build with Docker 20.10.5 + support for rootless dind
  image: jlu5/drone-docker
  settings:
    repo: ovdnet/inspircd
    username:
      from_secret: docker_user
    password:
      from_secret: docker_password
    build_args:
      - IRCD_VERSION=3.9.0
      - "EXTRASMODULES=m_blockhighlight m_fakelist m_join0 m_opmoderated m_relaymsg m_xlinetools "
      - "CONFIGUREARGS=--enable-extras=m_sslrehashsignal.cpp --enable-extras=m_geo_maxmind.cpp"
      - BUILD_DEPENDENCIES=libmaxminddb-dev
      - RUN_DEPENDENCIES=libmaxminddb
  trigger:
    branch:
    - master

node:
  # These tags are specific to the drone.overdrivenetworks.com instance
  # Route these builds to machines with more powerful CPUs (otherwise it takes like 15 minutes to finish..)
  highcpu: "true"
