name: Build container
on:
  pull_request:
  push:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      DOCKER_REPO_PREFIX: inspircd
      DOCKER_REPO_NAME: inspircd-docker
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      INSP_VERSION: v3.10.0
    steps:
      - uses: actions/checkout@v2

      - name: Prepare environment
        run: |
          sudo apt-get -qq update
          sudo apt-get -y -o Dpkg::Options::="--force-confnew" install moby-engine moby-cli
          sudo apt-get install -y openssl parallel

      - name: Build container
        run: |
          docker swarm init --advertise-addr `ip addr s | grep global | grep -oE '((1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])\.){3}(1?[0-9][0-9]?|2[0-4][0-9]|25[0-5])' | head -n1`
          docker build --build-arg VERSION="${INSP_VERSION}" -t inspircd:testing .

      - name: Push container
        if: github.repository == 'inspircd/inspircd-docker' && github.ref == 'refs/heads/master'
        run: |
          if [ "$DOCKER_USERNAME" != "" ] && [ "$DOCKER_PASSWORD" != "" ]; then
            ./tools/tagging.sh "${DOCKER_REPO_PREFIX}/${DOCKER_REPO_NAME}" "${INSP_VERSION:-latest}" ""
            docker images "${DOCKER_REPO_PREFIX}/${DOCKER_REPO_NAME}"
            echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
            docker images --format "{{.Repository}}:{{.Tag}}" "${DOCKER_REPO_PREFIX}/${DOCKER_REPO_NAME}" | xargs -L 1 docker push
            docker run --rm -v "$(pwd)/:/data/:ro" -e "DOCKERHUB_USERNAME=$DOCKER_USERNAME" -e "DOCKERHUB_PASSWORD=$DOCKER_PASSWORD" -e "DOCKERHUB_REPO_PREFIX=$DOCKER_REPO_PREFIX" -e "DOCKERHUB_REPO_NAME=$DOCKER_REPO_NAME" sheogorath/readme-to-dockerhub
          fi
